--- 
abstract: A solderless way to wire up you application components
author: 
  - Stevan Little <stevan@iinteractive.com>
build_requires: 
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Bread-Board
no_index: 
  directory: 
    - inc
    - t
requires: 
  Moose: 0.33
  MooseX::AttributeHelpers: 0.07
  MooseX::Param: 0.02
  MooseX::Params::Validate: 0.04
  Sub::Current: 0.02
  Sub::Exporter: 0.972
tests: t/*.t
version: 0.03
