---
abstract: 'A solderless way to wire up your application components'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.21
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bread-Board
no_index:
  directory:
    - inc
    - t
requires:
  Class::MOP: 1.00
  Moose: 1.00
  MooseX::Clone: 0.05
  MooseX::Params::Validate: 0.14
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
